# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import helloWorld_pb2 as helloWorld__pb2


class GreeterStub(object):
    """Missing associated documentation comment in .proto file"""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.sayHello = channel.unary_unary(
                '/helloWorld.Greeter/sayHello',
                request_serializer=helloWorld__pb2.HelloRequest.SerializeToString,
                response_deserializer=helloWorld__pb2.HelloResponse.FromString,
                )


class GreeterServicer(object):
    """Missing associated documentation comment in .proto file"""

    def sayHello(self, request, context):
        """Missing associated documentation comment in .proto file"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GreeterServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'sayHello': grpc.unary_unary_rpc_method_handler(
                    servicer.sayHello,
                    request_deserializer=helloWorld__pb2.HelloRequest.FromString,
                    response_serializer=helloWorld__pb2.HelloResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'helloWorld.Greeter', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Greeter(object):
    """Missing associated documentation comment in .proto file"""

    @staticmethod
    def sayHello(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/helloWorld.Greeter/sayHello',
            helloWorld__pb2.HelloRequest.SerializeToString,
            helloWorld__pb2.HelloResponse.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)
